sonar.projectKey=kien21bn_mapstruct-sonar-demo
sonar.projectName=sonar-demo
sonar.organization=kien21bn

sonar.sources=src/main/kotlin
sonar.tests=src/test/kotlin
sonar.java.binaries=build/classes/kotlin/main
sonar.java.test.binaries=build/classes/kotlin/test

sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml